<?php
session_start();

// generic .htm to .php conversion

if (stristr($_SERVER['REQUEST_URI'], ".htm"))
{
$end =  stripos($_SERVER['REQUEST_URI'], '.htm') - 1;

$base = substr($_SERVER['REQUEST_URI'], 1, $end);

//die("new name is $base.php");

Header( "HTTP/1.1 301 Moved Permanently" );
Header( "Location: http://www.prontocommercial.com/$base.php" );
die();
}


//if (stristr($_SERVER['REQUEST_URI'], "/404.php") == false)  // don't send back a header if called directly
header("HTTP/1.0 404 Not Found");


// if you made it here, you aren't here because of an old page name





function SendMessage($Subject, $Message)
{
	$IPaddr = GetIP();
	$text = $Message;
	$html = '<html><body>'.nl2br($Message).'</body></html>';
	$crlf = "\n";

	$To = "prontocommercial";
	$To .= "@gmail.com";
		// the email address of the person receiving the email
	$From = addslashes("Web Surfer")."<anthony@prontocommercial.com>";
	$SendDate = date('r');

	$To = $To; //.", ".$cc;
	$headers = "MIME-Version: 1.0" . "\r\n";
	$headers .= "Content-type:text/html;charset=iso-8859-1" . "\r\n";
	$headers .= 'From: ' . $From . "\r\n";
	$headers .= 'Reply-To: ' . $replyto . "\r\n";

	//print("to: $To<br>subject: $Subject<br>headers: $headers<br>message:<br>$Message");
	$sent = mail($To,$Subject,$Message,$headers);

	if ($sent == true)
		return('1');
	else
		return('E');
}


//~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ -  	\\
//							 					\\
// Get the visitor's IP Address			\\
//												\\
//~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ -    \\

function GetIP()
{
if ($_SERVER)
{
	if ( $_SERVER[HTTP_X_FORWARDED_FOR] )
	{
	$realip = $_SERVER["HTTP_X_FORWARDED_FOR"];
	}
	elseif ( $_SERVER["HTTP_CLIENT_IP"] )
	{
	$realip = $_SERVER["HTTP_CLIENT_IP"];
	}
	else
	{
	$realip = $_SERVER["REMOTE_ADDR"];
	}
}
else
{
	if ( getenv( 'HTTP_X_FORWARDED_FOR' ) )
	{
	$realip = getenv( 'HTTP_X_FORWARDED_FOR' );
	}
	elseif ( getenv( 'HTTP_CLIENT_IP' ) )
	{
	$realip = getenv( 'HTTP_CLIENT_IP' );
	}
	else
	{
	$realip = getenv( 'REMOTE_ADDR' );
	}
}

return $realip;
}


$IPaddr = GetIP();
//print("Referrer name 2: ". $_SERVER['REQUEST_URI']);

if ($_SERVER['REQUEST_URI'] != "/404.php")
{
	$s=$_SERVER['REQUEST_URI'];
	$s=ereg_replace("&","|",$s);
	$raw=$s=ereg_replace("\?","|",$s);
	$Start = 3 + strpos($s,"|q=");
	if ($Start < 4)   //if not found
	{
		$raw="'q=' not found in |".$s."|";
		$Start = 3 + strpos($s,"|p=");  //try this for a Yahoo search
	}
	else
		$raw="'q=' found in |".$s."| at position ".$Start;
	$s=substr($s,$Start);
	$End=strpos($s,"|");

	if ($End > 0)
		$Searched=substr($s, 0, $End);
	else
		$Searched=$s;
	$Searched=eregi_replace("\+"," ",$Searched);
	$Searched=eregi_replace("%20"," ",$Searched);
	$Searched=eregi_replace("%25","%",$Searched);
	$Searched=eregi_replace("%3F","?",$Searched);

	$s=substr($_SERVER['REQUEST_URI'],7);
	$x = strpos($s,"/");
	if($x > 0)
		$SearchEngine = substr($s, 0, $x);
	else
		$SearchEngine = $s;
	$Message = "<p>Search Engine (Referrer): '$SearchEngine', Search Term: '$Searched'</p>\n";
	//die("Testing |$Message|");

	$Message .= "</p><p>(message generated by '".$_SERVER['PHP_SELF']."')</p>.";
}


// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ - - - -	\\
//																										\\
// If the new page wasn't found, we'll have to get input from the					\\
// visitor. The rest of the page is just a nicely done (if I do say so					\\
// myself) 404 Page Not Found error.														\\
//																										\\
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ - - - -	\\

	$Message = "<p>A request for page |".$_SERVER['REQUEST_URI']."| was unfilled because the page was missing.</p>";
	$Message .= "<p>The visitor at IP address ".$IPaddr.", ".gethostbyaddr($IPaddr)." could not be redirected because there is no replacement page.</p>";

	if ($_SERVER['REQUEST_URI'] == "/404.php")
		$Message .= "<p>Had this been a real error, you would have been told to stay calm and update the 404 error handler.</p>";
	else
		$Message .= "<p>The error handler page, 404.php, doesn't have a redirect page for this page. Please investigate ASAP.</p>";

	$Message .= "<p>User agent: ".  $_SERVER['HTTP_USER_AGENT'] . "</p>\n";

	$Message .= "<p>host name: ".  gethostbyaddr($_SERVER['REMOTE_ADDR']) . "</p>\n";
	if ($_SERVER['REQUEST_URI'] != "")
		$Message .= "<p>Referrer name: ".  $_SERVER['REQUEST_URI'] . "</p>\n";

	$Message .= "<p>(message generated by '".$_SERVER['PHP_SELF']."')</p>\n.\n";
	$Subject = $_SERVER['SERVER_NAME'].": Error From IP ".$IPaddr." Unsuccessful access to ".$_SERVER['REQUEST_URI'];

	//die("Subject: $Subject<br>Message: $Message");

	SendMessage($Subject, $Message);

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8>
	<base href="http://www.prontocommercial.com" >
	<title>404 Error - Page not found</title>
	<link rel="SHORTCUT ICON" href=
	"http://www.prontocommercial.com/favicon.ico">
	<?php include("./include/head.php"); ?>
	<style>
	#pause {display:none !important;}
	h1 {display:block !important;}
	</style>
	</head>

<body>
	<?php include("./include/top.php"); ?>
				<h1>Whoops! This web page is missing...</h1>

				<p>I know it's around here somewhere...We've done some
				remodeling and now the page you're requested is gone. We're really sorry! Heads will roll for this mix-up,
				you can be sure.</p>
				<?php

				if ($_SERVER['REQUEST_URI'])
					print ("<p>You were sent here by: '".  $_SERVER['REQUEST_URI'] . "' and there's a slight problem because</p>");
				print ("<p><span style='font-weight: bold;'>\n");
				if ($_SERVER['REQUEST_URI'] == $_SERVER['PHP_SELF'])
					print("(Testing me out, are you?)</span></p>\n");
				else
					print("\"http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].",\"</span> cannot be found.</p>\n");
				?>

				<p>
				If your error message has to do with a font not being loaded, please try reloading the page a few times
				Sometimes the new fonts aren't automatically loaded. Otherwise, click on one of the other
				choices on this page. Surely, you'll soon be on your way and forget about this little web page screw-up.</p>

				<p>
				Click on <a href="javascript:history.back()">RETURN</a> to
				return to the previous page.</p>

<p><br>&nbsp;</p>
<?php include("./include/bottom.php"); ?>
</body>
</html>
