<?php
require ("../include/authenticate.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html401/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Borrower Pages Documentation</title>
<script language="JavaScript" src="https://host373.ipowerweb.com/~lightnin/js/Common.js">
</script>
<link rel="stylesheet" href="../css/AdministrativeStyles.css" type="text/css">
<!--[if IE 6]>
<style type="text/css">
html
{
  scrollbar-base-color: #F4F4F4;
  scrollbar-arrow-color: #FFFFFF;
  scrollbar-track-color: #002179;
  scrollbar-face-color: #000099;
  scrollbar-3dlight-color: #000099;
}
</style>
<![endif]-->
</head>
<body>
<div class="Main" id="MainDIV">
<div class="Content" id="ContentDIV">
    <h1>Website Pages</i></h1>
	<table border="0" cellpadding="4" cellspacing="0" width="720">
		<tr>
			<td align='left' width="20%"><font size='2' color="#000099" face='Verdana'>
				<form action='ApplicantMaster.php'>
				<p align='left'><br /><input class='Submit' type='submit' value='LAPS Home' style='color:#fff;'></p>
				</form>
			</td>
			<td height="18" valign='middle' width="50%">
				<font face="Verdana" color="#000099"><?php print ("<b>Welcome, $RealName</b>");?></font></td>
			<td align='right' width="30%">
				<form action='SystemDocumentation.php'>
				<p align='left'><br /><input class='Submit' type='submit' value='Other Documentation'></p>
				</form>
			</td>
		</tr>
	</table>
	
	<table cellpadding="4" cellspacing="0" width="720">
         <tr>
          <td style='vertical-align: top; width: 209; text-align: right;'><font face="Verdana" size="2" color="#000099"><b>Name</b></font></td>
          <td style='width: 429; text-align: left;'><font face="Verdana" size="2" color="#000099"><b>Description</b></font></td>
         </tr>
<?php
	if ($UserLevel == "Admin")
	{
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>&nbsp;</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>&nbsp;</font></td>");
    	print ("</tr>");

    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>The home page. Has 2 &quot;Call for action&quot;");
      	print ("articles. Points to index1 and index2</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index1.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A Call for action article - easy to change</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index2.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Another Call for action article - easy to change</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index3.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Another Call for action article - easy to change</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>LoanAppShort.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>OnLine Loan Application</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>LoanAppDB.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Adds the borrowers application to the database, then ");
      	print ("calls the AAA Credit credit card processing page</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>LoanAppShort.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Confirmation Page for Loan Application. Allows ");
      	print ("borrower to review and correct application data before submitting.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>OrderCreditDirect.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>To go directly to AAA Credit's credit card request ");
      	print ("screen without forcing the borrower to fill out another application.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>OrderCreditFailure.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>If the user<span style='mso-spacerun: yes'>&nbsp; </span>information ");
      	print ("isn't in the cookie that AAA Credit reads to validate the user, this ");
      	print ("screen is displayed.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>OrderCreditSuccess.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Page to return that AAA Credit returns to upon ");
      	print ("completion of them taking the credit card information</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>LoanTypes.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Lists our various loan types</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Rates.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Discusses interest rates</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Answers.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Lists the various pages borrowers can look for ");
      	print ("information. Calls WhatsInvolved.php, Documentation.php, credit.php, FAQ.php,");
      	print ("Glossary.php, and eBookRequest.php</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>WhatsInvolved.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Details what is involved with a refinance.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Documentation.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Lists the required borrower documentation when ");
      	print ("applying for a loan</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>FAQ.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Frequently Asked Questions</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Glossary.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A specialized mortgage term glossary</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>eBookRequest.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Has HTML form for of requesting a free download of");
      	print ("our Mortgage eBook</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>eBookRequestFailure.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>An error page for attempting to read the eBook</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>eBookRequestSuccess.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Provides download for the actual PDF file of the ");
      	print ("eBook</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>AboutUs.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Describes our company and our mission statement</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Calculators.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Has various financial calculators for use by visitors.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>ContactUs.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A page that describes how to reach Lightning Mortgage ");
      	print ("by phone, fax, e-mail, or mail</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>credit.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Has information about credit scores</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Feedback.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>The HTML format for site visitor requests for ");
      	print ("providing feedback</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Feedback.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>The back-end routine that sends the e-mail</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>FeedbackSent.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A &quot;success&quot; page to visitors who submit ");
      	print ("feedback</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Guarantee.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Our customer satisfaction guarantee page</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Legal.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Describes the legalese required info</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>MyLoanStatus.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A password protected page where borrowers can view ");
      	print ("their loan status information</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>PrivacyPolicy.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Describes our company 's privacy policy</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>RebateRequestFailure.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>RebateRequestSuccess.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>UpfrontMortgageBroker.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Discusses the Upfront Mortgage Broker &reg; program</font></td>");
    	print ("</tr>");    	
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>AffiliateLinks.php</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Lists website we have reciprocal links with</font></td>");
    	print ("</tr>");    	
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>SiteMap</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Provides a table of contents to web visitors</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td valign='top' x:str='Miscellaneous ' width='209' text-align='right'><font ");
      	print ("face='Verdana' size='2' color='#000099'>Miscellaneous</font></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>404.shtml</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Custom &quot;Page not found error&quot; page</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>../bad-credit-mortgage-styles.css</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>The Cascading Style Sheet used by these pages</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>favicon.ico</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Custom Icon visitors see when the bookmark the ");
      	print ("website</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Outlook AutoReply Macro.txt</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Outlook Auto-reply customized messages when ");
      	print ("applications and credit reports are received</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Common.js</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>In /js subdirectory - common JavaScript functions</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>LoanAppValidation.js</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>In /js subdirectory -Loan App editing JavaScript");
      	print ("functions</font></td>");
    	print ("</tr>");
    }
    else
	{
    	print ("<tr>");
     	print ("<td valign='top' class='xl25' width='209' text-align='right'><font face='Verdana' size='2'");
      	print ("color='#000099'>&nbsp;</font></td>");
     	print ("<td class='xl26' style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>&nbsp;</font></td>");
    	print ("</tr>");

    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>www home page. Has 2 &quot;Call uu tttt&quot;");
      	print ("articles. Points uu index1 and index2</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index1#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A Call uu tttt article - easy uu change</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>index2#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Anowwwr Call uu tttt article - easy uu change</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>XxxxAppShort#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>OnLine Xxxx qqppyyation</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>XxxxAppDB#rew</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Adds www borrowers qqppyyation uu www database, wwwn");
      	print ("calls www AAA ficqlj card processing page</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>XxxxAppShort#rew</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Confirmation Page for Xxxx qqppyyation. Allows");
      	print ("oorrower uu review and correct qqppyyation data before submitting.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>ee0%ficqljDirect#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>uu go directly uu AAA ficqlj's ficqlj card request");
      	print ("screen without forcing www borrower uu fill out anowwwr qqppyyation</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>ee0%ficqljFailure#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>If www user<span style='mso-spacerun: yes'>&nbsp; </span> xxx cccc");
      	print ("isn't in www cookie www AAA ficqlj reads uu validate www user, this");
      	print ("screen is displayed.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>ee0%ficqlj xxx ttt#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Page uu return www AAA ficqlj returns uu upon");
      	print ("completion of wwwm taking www ficqlj card  xxx cccc</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>XxxxTypes#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Pppp our various Xxxx types</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Rates#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Discusses  xxx cccc rates</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Answers#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Pppp www various pages borrowers can look for");
      	print (" xxx cccc. Calls WhatsInvolved, Documentation, ficqlj, FAQ,");
      	print ("Glossary, and eBookRequest</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>WhatsInvolved#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Details what is involved with a refinance.</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Documentation#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Pppp www required borrower documentation when");
      	print ("applying for a Xxxx</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>FAQ#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Frequently Asked Questions</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Glossary#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A specialized dpca term glossary</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>eBookRequest#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Has HTML form for of requesting a free download of");
      	print ("our dpca eBook</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>eBookRequestFailure#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>An error page for attempting uu read www eBook</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>eBookRequest xxx ttt#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Provides download for www actual PDF file of www");
      	print ("eBook</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>AboutUs#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'> xxx cccc our company and our mission statement</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Calculauurs#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Has various financial calculauurs for use by visiuurs</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>ContactUs#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A page www  xxx cccc how uu reach Lightning dpca");
      	print ("by phone, fax, e-mail, or mail</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>ficqlj#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Has  xxx cccc about ficqlj scores</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Feedback#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>www HTML format for site visiuur requests for");
      	print ("providing feedback</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Feedback#rew</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>www back-end routine www sends www e-mail</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>FeedbackSent#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A &quot; xxx ttt&quot; page uu visiuurs who submit");
      	print ("feedback</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Guarantee#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Our cusuumer satisfaction guarantee page</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Legal#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'> xxx cccc www legalese required info</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>MyXxxxStatus#rew</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>A password protected page where borrowers can view");
      	print ("wwwir Xxxx status  xxx cccc</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>PrivacyPolicy#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'> xxx cccc our company 's privacy policy</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>RebateRequestFailure#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>RebateRequest xxx ttt#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>UpfrontdpcaBroker#pcx</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Discusses www Upfront dpca Broker program</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td valign='top' x:str='Miscellaneous ' width='209' text-align='right'><font ");
      	print ("face='Verdana' size='2' color='#000099'>Miscellaneous</font></td>");
     	print ("<td style='width: 429; text-align: left;'></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>404.shtml</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Cusuum &quot;Page not found error&quot; page</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>favicon.ico</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Cusuum Icon visiuurs see when www bookmark www");
      	print ("website</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Outlook AuuuReply Macro.txt</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Outlook Auuu-reply cusuumized messages when");
      	print ("qqppyyations and ficqlj reports are received</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>Common.js</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>In /js subdirecuury - common JavaScript functions</font></td>");
    	print ("</tr>");
    	print ("<tr>");
     	print ("<td style='vertical-align: top; width: 209; text-align: right;'><font face='Verdana' size='2'");
      	print ("color='#000099'>XxxxAppValidation.js</font></td>");
     	print ("<td style='width: 429; text-align: left;'><font face='Verdana' size='2'");
      	print ("color='#000099'>In /js subdirecuury -Xxxx App editing JavaScript");
      	print ("functions</font></td>");
    	print ("</tr>");
    }
?>
 </table>
</div>
<!--  * * * * * * * * * * * * * * * * COMMON FOOTER  * * * * * * * * * * * * * * * -->
<?php include("../include/bottom.php"); ?>
<?php include("../include/top.php"); ?>
<!--  * * * * * * * * * * * * * * * * * * * End of COMMON HEADER * * * * * * * * * * * * * * * * * * -->
</body>
</html>
