<html>
<head>
<title>DBinput form handler</title>
</head>
<body>
<?php
/* this page receives and handles the data generated by 'DBinput.php' */
$Array["BorrowerName"] = trim ($Array ["BorrowerName"]);
$Array["Street"] = trim ($Array ["Street"]);
$Array["City"] = trim ($Array ["City"]);
$Array["Situation"] = trim ($Array ["Situation"]);

/* variables to access Database */

	$Host="localhost";
	$User="lightnin_Tony";
	$Password="ipowerwe";
	$DBname="lightnin_LoanApps";
	$TableName="TestDB";


    $DateEntered=date("m/d/y");
    $DOB="1901/01/01";
	$State="CA";
	$Zip="98765-4321";
	$WorkPhone="(999)888-7777";
	$HomePhone="(666)555-4444";
	$BestCallTime="6pm - 8 pm";
	$BestCallNumber="home";
	$email="tony@none.com";


	print ("Attempting to connect to the DBMS<BR>\n");
	/* first connect to the MySQL DBMS on this server */
	$Link=mysql_connect ($Host, $User, $Password) or die ('I cannot connect to the DBMS because: '.mysql_error());

	print ("Connect to the DBMS was successful!<BR>\n");
	/* Insert a record into the table */

    $Query = "INSERT into $TableName values
    ('0', '$DateEntered', '$Array[ApplicantName]', '$DOB', '$Array[Street]', '$Array[City]', '$State', '$Zip',
     '$WorkPhone', '$HomePhone', '$BestCallTime', '$BestCallNumber', '$email', '$Array[SSN]', '$Array[Situation]')";
	print("The query is:<br>$Query<br>\n");
	if (mysql_db_query ($DBname, $Query, $Link))
	{
		print("The query was successfully executed!<br>\n");
	}
	else
	{
		print("The query was could not be executed!<br>\n");
	}
	mysql_close($Link);
?>
</body>
</html>

