<?php
include('Mail.php');
include('Mail/mime.php');

function SendMessage($Subject, $Message)
{
	$IPaddr = GetIP();

    $To = "anthony";
    $To .= "@lightning-mortgage.com";
        // the email address of the person receiving the email
    $From = "\"A Web Site Visitor\" <web.visitor@lightning-mortgage.com>";
    	//$attachment = "/path/to/someFile.pdf";
        // the path to the file we are attaching to the email

    // Next we must build an array of email headers for the email.
    // This is structured slightly differently to the mail() function.
    // The array key is the header name. Remember that subject
    // is a header too!
	$SendDate = date('r');
    $Headers = array('From'    => $From,
					 'To'      => $To,
                     'Subject' => $Subject,
					 'Date'    => $SendDate);

$Params["host"] = "mail.lightning-mortgage.com";
$Params["port"] = "25";
$Params["auth"] = false;
//$params["username"] = "user";
//$params["password"] = "password";


    // Here we create the plaintext version of the email to be sent
    // $textMessage = "Dear John,\n\nThis is a fake email, I hope you enjoy it.\n\nFrom Jane.";
    // set our plaintext message
    // $mime->setTxtBody($textMessage);
    // attach the file to the email
    //$mime->addAttachment($attachment);

    // create a new instance of the Mail_Mime class
    $mime = new Mail_Mime();
    // set our HTML message
    $mime->setHtmlBody($Message);

    // This builds the email message and returns it to $body.
    // This should only be called after all the text, html and
    // attachments are set.
    $Body = $mime->get();

    // This builds the corresponding headers for the plaintext,
    // HTML and any other required headers. It also includes
    // the headers we created earlier by passing them as an argument.
    $Hdrs = $mime->headers($Headers);

    // Creates an instance of the mail backend that we can use
    // to send the email.
    $mail = &Mail::factory("smtp", $Params);

    // Send our email, according to the address in $To, the email
    // headers in $hdrs, and the message body in $body.
    $mail->send($To, $Hdrs, $Body);
}

//~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ -	\\
//								\\
// Get the visitor's IP Address	\\
//								\\
//~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ -	\\

function GetIP()
{
  if ($_SERVER)
  {
    if ( $_SERVER[HTTP_X_FORWARDED_FOR] )
    {
      $realip = $_SERVER["HTTP_X_FORWARDED_FOR"];
    }
    elseif ( $_SERVER["HTTP_CLIENT_IP"] )
    {
      $realip = $_SERVER["HTTP_CLIENT_IP"];
    }
    else
    {
      $realip = $_SERVER["REMOTE_ADDR"];
    }
  }
  else
  {
    if ( getenv( 'HTTP_X_FORWARDED_FOR' ) )
    {
      $realip = getenv( 'HTTP_X_FORWARDED_FOR' );
    }
    elseif ( getenv( 'HTTP_CLIENT_IP' ) )
    {
      $realip = getenv( 'HTTP_CLIENT_IP' );
    }
    else
    {
      $realip = getenv( 'REMOTE_ADDR' );
    }
  }

  return $realip;
}


// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ - - - -	\\
//																		\\
// If the new page wasn't found, we'll have to get input from the	 	\\
// visitor. The rest of the page is just a nicely done (if I do say so	\\
// myself) 403 Page Not Found error.									\\
//																		\\
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ - - - -	\\

$IPaddr = GetIP();

	$Message  = "<html>";
	$Message .= "<body style='font-family:Verdana,Arial,Helvetica,sans-serif;font-size:small;'>";
	$Message .= "<p>A request for page '".$REQUEST_URI."' was unfilled because the page was missing.</p>";
	$Message .= "<p>The visitor at IP address ".$IPaddr.", ".gethostbyaddr($IPaddr)." could not be redirected because there is no replacement page.</p>";
	
	if ($REQUEST_URI == $_SERVER['PHP_SELF'])
		$Message .= "<p>Had this been a real error, you would have been told to stay calm and update the 403 error handler.</p>";
	else
		$Message .= "<p>Please investigate this 'illegal' action ASAP.</p>";

	$Message .= "<p>User agent: ".  $_SERVER['HTTP_USER_AGENT'] . "</p>\n";
	
	$Message .= "<p>host name: ".  gethostbyaddr($_SERVER['REMOTE_ADDR']) . "</p>\n";
if ($_SERVER['HTTP_REFERER'] != "")
	$Message .= "<p>Referrer name: ".  $_SERVER['HTTP_REFERER'] . "</p>\n";

	$Message .= "<p>(message generated by '".$_SERVER['PHP_SELF']."')</p>";
	$Message .= "</body></html>";
	$Subject = "Error From IP ".$IPaddr." Unsuccessful Redirect of Web Page ".$REQUEST_URI;

	SendMessage($Subject, $Message);
?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html401/loose.dtd">
<html>
<head>
<base href="http://www.lightning-mortgage.com/">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>403 - Forbidden</title>
<link rel="stylesheet" href="http://www.lightning-mortgage.com/css/AdministrativeStyles.css" type="text/css">
<link rel="stylesheet" href="./css/Tabs.css" type="text/css">
</head>
<body>
<?php include('./include/top-root.php'); ?>
		<h1 id="Small" style='text-align:center;font-size:xx-large;'> Sorry, but I cannot allow you to do that!</h1>
<?php include('./include/bottom-root.php'); ?>
</body>
</html>
